#!/usr/bin/env python3
"""Project generation engine for Auto Development Studio."""
import json, os, shutil, sys, zipfile
from pathlib import Path

def generate(input_data: dict, output_dir: str):
    name = input_data.get("project_name", "my-app").replace(" ", "-").lower()
    color = input_data.get("brand_color", "#ff6600")
    use_auth = input_data.get("use_auth", "yes") == "yes"
    use_db = input_data.get("use_db", "yes") == "yes"
    models = [m.strip() for m in input_data.get("models", "").split(",") if m.strip()]
    pages = [p.strip() for p in input_data.get("pages", "").split(",") if p.strip()]

    out = Path(output_dir) / name
    if out.exists():
        shutil.rmtree(out)
    out.mkdir(parents=True)

    (out / "app" / "routers").mkdir(parents=True)
    (out / "app" / "models").mkdir(parents=True)
    (out / "app" / "templates").mkdir(parents=True)
    (out / "app" / "static" / "css").mkdir(parents=True)
    (out / "data").mkdir()
    (out / "scripts").mkdir()

# ___ pyproject.toml ___
    sqlalchemy_dep = '    "sqlalchemy>=2.0.36",\n' if use_db else ""
    jinja_dep = '    "jinja2>=3.1.4",\n' if use_auth else ""
    authlib_dep = '    "authlib>=1.4.0",\n' if use_auth else ""
    (out / "pyproject.toml").write_text(f"""[project]
name = "{name}"
version = "0.1.0"
description = "Generated by Auto Development Studio"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.115.0",
    "uvicorn[standard]>=0.32.0",
{sqlalchemy_dep}{jinja_dep}{authlib_dep}    "python-dotenv>=1.0.1",
    "pydantic-settings>=2.6.0",
]
[build-system]
requires = ["setuptools>=75.0.0"]
build-backend = "setuptools.build_meta"
""")

    # ___ config.py ___
    auth_client_id = '    google_client_id: str = ""\n' if use_auth else ""
    auth_client_secret = '    google_client_secret: str = ""\n' if use_auth else ""
    (out / "app" / "config.py").write_text(f"""from pydantic_settings import BaseSettings
from dotenv import load_dotenv
load_dotenv()

class Settings(BaseSettings):
    app_name: str = "{name}"
    debug: bool = True
{auth_client_id}{auth_client_secret}    session_secret: str = "change-me"
    model_config = {{"env_file": ".env", "env_file_encoding": "utf-8"}}
""")

    # ___ database.py ___
    (out / "app" / "database.py").write_text(f"""import os
from sqlalchemy import create_engine
from sqlalchemy.orm import sessionmaker, DeclarativeBase
from app.config import Settings

settings = Settings()
data_dir = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "data")
os.makedirs(data_dir, exist_ok=True)
db_url = f"sqlite:///{{os.path.join(data_dir, 'app.db')}}"
engine = create_engine(db_url, connect_args={{"check_same_thread": False}})
SessionLocal = sessionmaker(autocommit=False, autoflush=False, bind=engine)

class Base(DeclarativeBase):
    pass

def get_db():
    db = SessionLocal()
    try:
        yield db
    finally:
        db.close()
""")

    # ___ models ___
    model_code = ""
    for m in models:
        model_code += f"""
class {m}(Base):
    __tablename__ = "{m.lower()}"
    id = Column(String, primary_key=True, default=lambda: str(uuid.uuid4()))
    name = Column(String, nullable=True)

"""
    if model_code:
        all_models = "\n".join(f"from app.models.{m.lower()} import {m}" for m in models)
    else:
        all_models = ""

    models_init = "from sqlalchemy import Column, String" if model_code else "# No models defined"
    if model_code:
        models_init = """import uuid
from sqlalchemy import Column, String
from app.database import Base

""" + model_code

    (out / "app" / "models" / "__init__.py").write_text("")
    (out / "app" / "models" / "user.py").write_text(models_init)

    # ___ main.py ___
    auth_import = 'from app.routers import auth' if use_auth else ''
    auth_init = 'auth._init_templates(templates)\n    app.include_router(auth.router)' if use_auth else ''
    db_import = 'from app.database import Base, engine\n' if use_db else ''

    (out / "app" / "main.py").write_text(f"""import os
from fastapi import FastAPI, Request
from fastapi.staticfiles import StaticFiles
from starlette.middleware.sessions import SessionMiddleware
from starlette.templating import Jinja2Templates
from app.config import Settings
{db_import}{auth_import}

settings = Settings()
app = FastAPI(title=settings.app_name, debug=settings.debug)
templates = Jinja2Templates(directory=os.path.join(os.path.dirname(__file__), "templates"))
app.add_middleware(SessionMiddleware, secret_key=settings.session_secret, max_age=7*24*60*60)
static_dir = os.path.join(os.path.dirname(__file__), "static")
os.makedirs(static_dir, exist_ok=True)
app.mount("/static", StaticFiles(directory=static_dir), name="static")
{"Base.metadata.create_all(bind=engine)" if use_db else ""}
{auth_init}

@app.get("/")
async def index(request: Request):
    return templates.TemplateResponse(request, "index.html", {{"request": request}})

@app.get("/health")
async def health():
    return {{"status": "ok"}}
""")

    # ___ .env ___
    auth_env = "GOOGLE_CLIENT_ID=your-google-client-id\nGOOGLE_CLIENT_SECRET=your-google-client-secret" if use_auth else ""
    (out / ".env.example").write_text(f"""APP_NAME={name}
DEBUG=true
{auth_env}
SESSION_SECRET=change-me
""")

    # ___ .gitignore ___
    (out / ".gitignore").write_text("__pycache__/\n.venv/\n*.db\n.env\nnode_modules/\n")

    # ___ templates/index.html ___
    title = name.replace("-", " ").title()
    (out / "app" / "templates" / "base.html").write_text(f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{% block title %}}{name}{{% endblock %}}</title>
    <script src="https://cdn.tailwindcss.com"></script>
    <script>tailwind.config = {{{{ theme: {{ extend: {{ colors: {{ brand: '{{{color}}}' }} }} }} }}}}</script>
</head>
<body class="bg-gray-50 min-h-screen flex flex-col">
    <nav class="bg-white shadow-sm border-b border-gray-200 px-6 py-4">
        <a href="/" class="font-semibold text-lg">{title}</a>
    </nav>
    <main class="flex-1">{{% block content %}}{{% endblock %}}</main>
</body>
</html>""")

    (out / "app" / "templates" / "index.html").write_text(f"""{{% extends "base.html" %}}
{{% block content %}}
<div class="max-w-3xl mx-auto px-4 py-20 text-center">
    <h1 class="text-4xl font-bold text-gray-900 mb-4">{title}</h1>
    <p class="text-xl text-gray-600 mb-8">{input_data.get("tagline", "Built with Auto Development Studio")}</p>
    <a href="/health" class="inline-block px-8 py-3 text-white font-semibold rounded-xl" style="background-color: {color}">Check Health</a>
</div>
{{% endblock %}}""")

    # ___ static/css/input.css ___
    (out / "app" / "static" / "css" / "input.css").write_text("/* Generated by Auto Development Studio */")

    # ___ __init__ files ___
    (out / "app" / "__init__.py").write_text("")
    (out / "app" / "routers" / "__init__.py").write_text("")

    # ___ ZIP it ___
    zip_path = Path(output_dir) / f"{name}.zip"
    with zipfile.ZipFile(zip_path, "w", zipfile.ZIP_DEFLATED) as zf:
        for root, dirs, files in os.walk(out):
            for f in files:
                fp = os.path.join(root, f)
                arc = os.path.relpath(fp, out.parent)
                zf.write(fp, arc)

    print(f"Generated {{name}} at {{output_dir}}")
    print(f"ZIP: {{zip_path}}")

if __name__ == "__main__":
    import argparse
    parser = argparse.ArgumentParser()
    parser.add_argument("--input")
    parser.add_argument("--output")
    args = parser.parse_args()
    with open(args.input) as f:
        data = json.load(f)
    generate(data, args.output)